return {}
-- return {
--   "saghen/blink.cmp",
--   event = { "LspAttach" },
--   dependencies = "rafamadriz/friendly-snippets",
--
--   version = "v0.*",
--
--   opts = {
--     highlight = {
--       use_nvim_cmp_as_default = true,
--     },
--     -- set to 'mono' for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
--     -- adjusts spacing to ensure icons are aligned
--     nerd_font_variant = "mono",
--     keymap = {
--       show = "<C-space>",
--       hide = "<C-e>",
--       accept = "<Enter>",
--       select_prev = { "<Up>", "<C-p>" },
--       select_next = { "<Down>", "<C-n>" },
--
--       show_documentation = {},
--       hide_documentation = {},
--       scroll_documentation_up = "<C-b>",
--       scroll_documentation_down = "<C-f>",
--
--       snippet_forward = "<Tab>",
--       snippet_backward = "<S-Tab>",
--     },
--
--     windows = {
--       autocomplete = {
--         border = "single",
--       },
--       documentation = {
--         border = "single",
--       },
--     },
--
--     accept = { auto_brackets = { enabled = true } },
--
--     trigger = { signature_help = { enabled = true } },
--   },
-- }
